# Aktifkan Dropbear
NO_START=0

# Port standar atau port alternatif (misal: 2222)
DROPBEAR_PORT=109

# Argumen keamanan tambahan
DROPBEAR_EXTRA_ARGS="-s -w -p 143"

# Opsional: Banner (jika diperlukan)
DROPBEAR_BANNER="/etc/banner.txt"

# Hostkey (gunakan default atau tentukan path)
# DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"
# DROPBEAR_ECDSAKEY="/etc/dropbear/dropbear_ecdsa_host_key"

# Receive window (biarkan default)
DROPBEAR_RECEIVE_WINDOW=65536
