#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
CITY=$(cat /etc/xray/city)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
echo -e "\e[32mloading...\e[0m"
clear
read -p " Trial Duration (Minutes) : " pup
domain=$(cat /etc/xray/domain)
masaaktif=1
Quota=5
iplimit=4
user=Trial-VM`</dev/urandom tr -dc 0-9 | head -c3`
clear 
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "+$pup minutes" +"%Y-%m-%d %H:%M")
# Schedule killtrial after specified minutes
echo "killtrial vmess $user" | at now + $pup minutes >/dev/null 2>&1
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
exp=$(date -d "+$pup minutes" +"%Y-%m-%d %H:%M")
sed -i '/#vmessgrpc$/a\## '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
asu=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
ask=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
grpc=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
asik=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "quiz.int.vidio.com",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}  
EOF`
usik=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "141.193.213.21",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "blog.webex.com.${domain}",
      "tls": "none"
}  
EOF`
usuk=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "api/v1/token/hetoken/vmess",
      "type": "none",
      "host": "myim3-he.ioh.co.id",
      "tls": "none"
}  
EOF`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
vmess_base643=$( base64 -w 0 <<< $vmess_json3)
vmess_base644=$( base64 -w 0 <<< $vmess_json4)
vmess_base645=$( base64 -w 0 <<< $vmess_json5)
vmess_base646=$( base64 -w 0 <<< $vmess_json6)
vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"
vmesslink4="vmess://$(echo $asik | base64 -w 0)"
vmesslink5="vmess://$(echo $usik | base64 -w 0)"
vmesslink6="vmess://$(echo $usuk | base64 -w 0)"
systemctl restart xray > /dev/null 2>&1
service cron restart > /dev/null 2>&1


cat >/var/www/html/vmess-$user.txt <<-END

=========================
=========================
# Format Vmess WS TLS

- name: Vmess-$user-WS TLS
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess WS Non TLS

- name: Vmess-$user-WS Non TLS
  type: vmess
  server: ${domain}
  port: 80
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess gRPC

- name: Vmess-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vmess
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-grpc

# 📡 VMESS ACCOUNT
# 👤 Username : ${user}
# 🌐 Host : ${domain}
# 📦 Quota : ${Quota} GB
# 📱 Limit IP : ${iplimit}
# 🆔 UUID : ${uuid}
# 🔗 TLS : ${vmesslink1}
# 🔗 NTLS : ${vmesslink2}
# 🔗 gRPC : ${vmesslink3}

END
if [ ! -e /etc/vmess ]; then
  mkdir -p /etc/vmess
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g');
d=$(( ${c} * 1024*1024*1024 ));

if [[ ${c} != "0" ]]; then
echo "${d}" > /etc/vmess/${user}
fi
DATADB=$(cat /etc/vmess/.vmess.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vmess/.vmess.db
fi

clear
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<b>📡 VMESS ACCOUNT</b>
━━━━━━━━━━━━━━━━━━━━
👤 Username : <code>${user}</code>
🌐 Host : <code>${domain}</code>
📦 Quota : <code>${Quota} GB</code>
📱 Limit IP : <code>${iplimit}</code>
🆔 UUID : <code>${uuid}</code>
━━━━━━━━━━━━━━━━━━━━
🔗 TLS : <code>${vmesslink1}</code>
🔗 NTLS : <code>${vmesslink2}</code>
🔗 gRPC : <code>${vmesslink3}</code>
━━━━━━━━━━━━━━━━━━━━
🌐 Config Lain
━━━━━━━━━━━━━━━━━━━━
🔗 VIDIO : <code>${vmesslink4}</code>
🔗 ISAT EDU : <code>${vmesslink5}</code>
🔗 ISAT OPOK : <code>${vmesslink6}</code>
━━━━━━━━━━━━━━━━━━━━
⏳ Masa Aktif : <code>$pup Menit</code>
━━━━━━━━━━━━━━━━━━━━
💾 <a href='https://${domain}:81/vmess-$user.txt'>OpenClash Format</a>
"

[ -z "$NO_NOTIF" ] && curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
clear
echo -e "📡 VMESS ACCOUNT"
echo -e "━━━━━━━━━━━━━━━━━━━━"
echo -e "👤 Username : ${user}"
echo -e "🌐 Host : ${domain}"
echo -e "📦 Quota : ${Quota} GB"
echo -e "📱 Limit IP : ${iplimit}"
echo -e "🆔 UUID : ${uuid}"
echo -e "━━━━━━━━━━━━━━━━━━━━"
echo -e "🔗 TLS : ${vmesslink1}"
echo -e "🔗 NTLS : ${vmesslink2}"
echo -e "🔗 gRPC : ${vmesslink3}"
echo -e "━━━━━━━━━━━━━━━━━━━━"
echo -e "🌐 Config Lain"
echo -e "━━━━━━━━━━━━━━━━━━━━"
echo -e "🔗 VIDIO : ${vmesslink4}"
echo -e "🔗 ISAT EDU : ${vmesslink5}"
echo -e "🔗 ISAT OPOK : ${vmesslink6}"
echo -e "━━━━━━━━━━━━━━━━━━━━"
echo -e "💾 Format OpenClash : https://${domain}:81/vmess-\$user.txt"
echo -e "Aktif Selama : $pup Menit"
echo -e "Berakhir Pada : $(date -d "+$pup minutes" +"%d %b, %Y %H:%M")"
echo ""

