#!/bin/bash
function restore(){
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
clear
# ==========================================
# Getting
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC      INPUT LINK BACKUP VPS       $NC"|lolcat
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "input Link backup :  " -e url
echo -e ""
wget -O backup.zip "$url"
unzip backup.zip
echo "Start Restore"
cd /root/backup
cp  passwd /etc/
cp  group /etc/
cp  shadow /etc/
cp  gshadow /etc/
cp  crontab /etc/
cp .ssh.db /etc/ssh/
cp .vmess.db /etc/vmess/
cp .vless.db /etc/vless/
cp .trojan.db /etc/trojan/
cp .shadowsocks.db /etc/shadowsocks/
cp -r kyt /var/lib/
cp -r xray /etc/
cp -r html /var/www/
cp -r limit /etc/kyt/
cp -r vmess /etc/
cp -r trojan /etc/
cp -r vless /etc/
cp -r shadowsocks /etc/
notif_restore
rm -rf /root/backup
rm -f backup.zip
}

function notif_restore(){
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
◇━━━━━━━━━━━━━━◇
   ⚠️ RESTORE NOTIF⚠️
     Detail Restore VPS
◇━━━━━━━━━━━━━━◇
     Restore Vps Done
◇━━━━━━━━━━━━━━◇
  BY BOT : 🤖@WendiVpn Tunnel
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
restore